#!/bin/bash

stty -echoctl
set -e

IMP3R4T1V35=()
POS1710N4L5=()
T4RG3TL3V3L="easy"

M0D35=()

export GENIUS_NAME=""
export B0TN371D3N71F13R="CNSL_307N37"

function n035c4p3(){
    h4ck3r0u7pu7 "\033[32mTHERE IS NO ESCAPE.\033[0m"
    # put relevant evil capture code here
    3sc4p3 6
}

escapescape=3
escapecnt=0
function 3sc4p3() {
    
    clear

    if [ $1 ]
    then
        loop=$1
    else
        loop=10
    fi

    c0un73r=1
    sleep 0.2 
    while [ $c0un73r -le $loop ]
        do
            r=$((c0un73r % 2 ))

            if [ "$r" -eq 0 ]
            then
                h4ck3r0u7pu7 "\033[34m\t\tNO ESCAPE.\033[0m"
            else
                h4ck3r0u7pu7 "\033[32m\v\v\tNO ESCAPE.\033[0m"
            fi
          sleep 0.1
          ((c0un73r++))
        done
        if [[ "$escapecnt != $escapescape" ]]
        then
            while [ "$loop" -ge  2 ]
            do
                l=$((loop - 2))
                loop=$l
                3sc4p3 $l
                ((escapecnt++)) 
            done
        else
            return 1
        fi

}

function exfil(){
    h4ck3r0u7pu7  "\033[32m\v\v\tNnN\vo0O\vEe33\vS55S\vCCCC\vA4Å\vPpP\v3Ee.\033[0m"
    h4ck3r0u7pu7  "\033[32m\t\t\tNnN\to0O\tEe33\tS55S\tCCCC\tA4Å\tPpP\t3Ee.\033[0m"
    h4ck3r0u7pu7  "\033[32mNnNo0OEe33S55SCCCCA4ÅPpP3Ee.\033[0m"
    for i in {1..10..2}
    do
        msg="\033[32mNnNo0OEe33S55SCCCCA4ÅPpP3Ee.\033[0m"
        msg2="\033[33mNnNo0OEe33S55SCCCCA4ÅPpP3Ee.\033[0m"
        msg3="\033[34mNnNo0OEe33S55SCCCCA4ÅPpP3Ee.\033[0m"
        h4ck3r0u7pu7 $msg $msg2 $msg3 $msg2
    done

}

function h4ck3r0u7pu7(){
  echo -e "$@"
}

trap n035c4p3 SIGINT 
trap exfil EXIT

function p4r53Argum3n75(){

  while [[ $# -gt 0 ]]; do
    imp3r4t1v3="$1"

    case $imp3r4t1v3 in
      --ddos)
      IMP3R4T1V35+=("12xx")
      shift
      ;;
      --hackBank|--hackFacebook|--hackiCloud|--hackOnlyFans)
      IMP3R4T1V35+=("1337")
      shift
      ;;
      --hackJH|--hackJohnHammond)
      IMP3R4T1V35+=("1338")
      T4RG3TL3V3L="unlikely"
      shift
      ;;
      --hackRoblox)
      IMP3R4T1V35+=("1341")
      shift
      ;;
      --hackNsa)
      IMP3R4T1V35+=("1342")
      shift
      ;;
      --swat)
      IMP3R4T1V35+=("1401")
      shift
      ;;
      -a|--ascii)
      M0D35+=("3001")
      SK1P1N7R0=1
      INPU7="$2"
      shift
      shift
      ;;
      *)                        # unkn0wn t0 $0 h4ck3r5
      POS1710N4L5+=("$1")
      shift
      ;;
    esac
  done
  set -- "${POS1710N4L5[@]}"

  if [[ ${#IMP3R4T1V35} -gt 0 ]]; then
    unset SK1P1N7R0
  fi
}

function pr1n7Bann3r() {
  b4d45545k11=$(cat assets/banner)
  b4d455b4nn3r="
   \033[35m''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''\033[0m   
\033[32m$b4d45545k11\033[0m
   \033[35m''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''\033[0m   
   \033[32m-                       TH3 3 15 51L3N7 4ND 1Nv151BL3                        -\033[0m   
   \033[35m..............................................................................\033[0m   
"
  h4ck3r0u7pu7 "$b4d455b4nn3r"
}

function in17() {
  h4ck3r0u7pu7 "\033[33;5;1mLOADING\033[0m...\n"
  sleep 8
  h4ck3r0u7pu7 "\033[32mSuite fully loaded.\033[0m"
}

function d3pl0yStr1k3() {
  for h4ckm0d3 in "${IMP3R4T1V35[@]}"; do
    if [[ $h4ckm0d3 -eq "1341" ]]; then
      sleep 2
      clear
      . ops/roblox
    elif [[ $h4ckm0d3 -eq "1342" ]]; then
      clear
      pr1n7Bann3r
      h4ck3r0u7pu7 "NSA h@ck detected."
      h4ck3r0u7pu7 "\033[33;5;1mLOADING\033[0m advanced features..."
      sleep 12
      clear
      . ops/nsa
    fi
  done
}

function m0st1mp0r74n7Func710n() {
  if [[ ${#IMP3R4T1V35} -eq 0 ]]; then
    sleep 1
    h4ck3r0u7pu7 "Type ATTACK to start the hacking."
    sleep 1
    read h4ck3r1npu7
    h4ck3r0u7pu7 "Okay."
  elif [[ ${#IMP3R4T1V35} -gt 0 ]]; then
    d3pl0yStr1k3
  fi
}

function actualM41n() {
  trap SIGINT SIGTERM SIGKILL
    for mode in "${M0D35[@]}"; do
    if [[ $mode -eq "3001" ]]; then
      utilities/thecaexee "$INPU7"
    fi
  done
}

function m41n() {
  if [[ -z $SK1P1N7R0 ]]; then
    pr1n7Bann3r
    in17
    m0st1mp0r74n7Func710n
  else
    actualM41n
  fi
}

p4r53Argum3n75 "$@"
m41n
