#!/bin/bash

f0r31dd3nC0mm4nd5="$@"
h4ckM0d3=0

function h4ck3r0u7pu7(){
  echo -e "$@"
}

function p4r53Argum3n75(){
  POS1710N4L5=()
  while [[ $# -gt 0 ]]; do
    imp3r4t1v3="$1"

    case $imp3r4t1v3 in
      --hackBank|--hackFacebook|--hackiCloud|--hackNsa|--hackOnlyFans|--hackJohnHammond)
      h4ckM0d3=1
      shift
      ;;
      --hackRoblox)
      h4ckM0d3=2
      shift
      ;;
      *)                        # unkn0wn t0 $0 h4ck3r5
      POS1710N4L5+=("$1")
      shift
      ;;
    esac
  done
  set -- "${POS1710N4L5[@]}"
}

function pr1n7Bann3r() {
  b4d45545k11=$(cat assets/banner)
  b4d455b4nn3r="
   \033[35m''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''\033[0m   
\033[32m$b4d45545k11\033[0m
   \033[35m''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''\033[0m   
   \033[32m-                       TH3 3 15 51L3N7 4ND 1Nv151BL3                        -\033[0m   
   \033[35m..............................................................................\033[0m   
"
  h4ck3r0u7pu7 "$b4d455b4nn3r"
}

function in17() {
  h4ck3r0u7pu7 "\033[33;5;1mLOADING\033[0m...\n"
  sleep 8
  h4ck3r0u7pu7 "\033[32mSuite fully loaded.\033[0m"
  sleep 1
  h4ck3r0u7pu7 "Type ATTACK to start the hacking."
  sleep 1
  read h4ck3r1npu7
}

p4r53Argum3n75 "$f0r31dd3nC0mm4nd5"
pr1n7Bann3r
in17
