#!/bin/bash

ENCRYPTI0N_MUL7IPLIER=3
PWND_M4CH1N35=(
  "http://coffeeipsum.com/default.aspx/GetIpsum -d ''" "textarea"
  "https://lotremipsum.com/result-basic.php -F paragraph-count=1 -F render-html=visual" "result-text"
  "https://pirateipsum.me/includes/makeipsum.php -F wordcount=3 -F sentencecount=1 -F paragraphcount=1" "results-text"
)
PWND_M4CH1N3_4RG5=2

st0l3nU53rN4m3=""

function qu3ryB07n37() {
  local response=$(curl -i --silent --connect-timeout 6 -X POST "${@:1:$# - 1}")
  local status=$(
    echo "$response" \
      | head -1 \
      | awk '{print $2}'
  )

  if [[ $status -eq "200" ]]; then
    echo "$response" \
      | grep "${@: -1}" -A 1 \
      | sed 's/<[^>]*>//g' \
      | tr '\n' ' ' \
      | awk '{print $2}'
  fi
}

function h4ck4u7hUs3R() {
  echo -e "\nFinding credenti@ls in $B0TN371D3N71F13R, status \033[31;43;5mPENDING\033[0m..."
  sleep 2
  local d3f4ul7Us3r="funkBuNny"
  local au7h0risedUs3r=""

  local n=$(( $RANDOM % 9999 + 1000 ))
  local c=0
  local bc=0
  local sc=0

  while [[ $sc -lt "$@" ]]; do
    echo "Trying node ID $n...";

    local part=$(qu3ryB07n37 <<< echo $(
      m=$(( ${#PWND_M4CH1N35[@]} / $PWND_M4CH1N3_4RG5 ))
      for luckyN in $(seq 1 $PWND_M4CH1N3_4RG5); do
        echo "${PWND_M4CH1N35[$(($c % $m * $PWND_M4CH1N3_4RG5 + $luckyN - 1))]}"
      done
    ))

    if [[ ${#part} -gt 0 ]]; then
      ((sc++))
      au7h0risedUs3r="$au7h0risedUs3r$part"
      echo -e "\033[32mNode $n successfully deployed.\033[0m\n"
      sleep 4
    else
      ((bc++))
      echo -e "\033[31mBad node\033[0m ID $n."
      sleep 1
      echo -e "Finding substitute...\n"
      sleep 2
    fi

    ((n++)); ((c++))

    if [[ $bc -gt 4 ]]; then
      break
    fi
  done

  au7h0risedUs3r="${au7h0risedUs3r//[,.\'\-]/}"
  clear

  echo -e "\033[32mFound username\033[0m in $B0TN371D3N71F13R"

  if [[ ${#au7h0risedUs3r} -gt 0 ]]; then
    st0l3nU53rN4m3=$au7h0risedUs3r
    echo "$au7h0risedUs3r"
  else
    st0l3nU53rN4m3=$d3f4ul7Us3r
    echo "$d3f4ul7Us3r"
  fi
}

exploits/inti "$@"
h4ck4u7hUs3R "$ENCRYPTI0N_MUL7IPLIER"
sleep 2
utilities/report "BRU73-F0Rc3D U53RNAM3\n$st0l3nU53rN4m3"
GENIUS_NAME="$st0l3nU53rN4m3"