#!/bin/bash

function stripFlattenHtml() {
  echo "$@" | sed 's/<[^>]*>//g' | tr '\n' ' '
}

if [[ -p /dev/stdin ]]; then
  while read -r line; do
    stripFlattenHtml "$line"
  done

else
  if [[ -f "$@" ]]; then
    cat "$@" | while read -r line; do
      stripFlattenHtml "$line"
    done

  else
    stripFlattenHtml "$@"
  fi
fi
