#!/bin/bash

output=""

source ./source/LIB.thecaexee

function h@ck3rW3lc0m3() {
  echo "$@" | while read -n1 char; do
    char="$(
      echo "$char" \
      | awk '{print toupper($0)}'
    )"

    the_ca_exee="_$char"

    if [[ -z "${!the_ca_exee}" ]]; then
      sleep .025

      echo "$output" | while read -r line; do
        line="$(echo "$line" | xxd -r -p)"
        printf "%s\033[32;1m$line\033[0m"
        sleep .175
        printf "%s\n"
      done

      output=""

    else
      j=0
      k=0
      output="$(echo -e "${!the_ca_exee}" | while read -r line; do

        echo "$output" | while read -r mine; do
          if [[ $k -eq $j ]]; then
            printf "%s$mine"
          fi
          (( k++ ))
        done

        echo "$line"
        (( j++ ))
      done)"

    fi
  done
}

function receiveTransmission() {
  echo -e "$1" | while IFS= read -n1 char; do
    printf "%s$2$char\033[0m"
    sleep .125
  done
  sleep 2
}

function monologue() {
  receiveTransmission "We've been awaiting you. " "\033[33;1m"
  receiveTransmission "You're actually late. " "\033[33;1m"
  receiveTransmission "We've been closely monitoring your tracks around the web, and we were reckoning you'd find this backdoor much sooner." "\033[33;1m"
  sleep 2
  receiveTransmission " It's too late now. We are no longer interested in doing business with you." "\033[33;1m"
  receiveTransmission " Tough luck, mate." "\033[33;1m"
  receiveTransmission " HAVE A GOOD DAY." "\033[31;1m"
}

if [[ -z $@ ]]; then
  echo "Welcome."
else
  receiveTransmission "Welcome to the" "\033[33;1m"
  h@ck3rW3lc0m3 "$@"
fi

monologue