#!/bin/bash

function receiveTransmission() {
  echo -e "$1" | while IFS= read -n1 char; do
    printf "%s$2$char\033[0m"
    sleep .125
  done
  sleep 2
}

function monologue() {
  receiveTransmission "We've been awaiting you. " "\033[33;1m"
  receiveTransmission "You're actually late. " "\033[33;1m"
  receiveTransmission "We've been closely monitoring your tracks around the web, and we were reckoning you'd find this backdoor much sooner." "\033[33;1m"
  sleep 2
  receiveTransmission " It's too late now. We are no longer interested in doing business with you." "\033[33;1m"
  receiveTransmission " Tough luck, mate." "\033[33;1m"
  receiveTransmission " HAVE A GOOD DAY." "\033[31;1m"
}

if [[ -z $@ ]]; then
  echo "Welcome."
else
  receiveTransmission "Welcome to the" "\033[33;1m"
  utilities/thecaexee "$@"
fi

monologue