#!/bin/bash

T4RG37="$@"
F_EXT=$(echo "$T4RG37" | awk '{print tolower($0)}')

function receiveTr4nsm1ss1on() {
  sleep 2
  cat "source/messages.$F_EXT" | while read -r m; do
    echo -e "$T4RG37 IR responds:\n\033[33;1m$m\033[0m\n"
    sleep 8
    echo -e "Attempting to apply counter-measures...\n"
    sleep 4
  done
}

function ep1c() {
  echo -e "\033[31;43mWARNING\033[0m: $T4RG37 IR servers are responding with counter-attack.\n"
  sleep 1
  echo -e "Decrypting response..."
  sleep 2
  echo -e "\033[32mDecryption key recovered\033[0m. Showing message...\n"
  receiveTr4nsm1ss1on
  clear
  echo -e "\033[32mHack successfully concluded\033[0m.\nOutcome: Next step: Contact $T4RG37 support.\n"
}

ep1c